#!perl

HELP "edit" => "Edit product list";

my $filename = 'spacetab.products';

sub command :Tab(edit) ($self, $cart, $command, @) {
    $command eq 'edit' or return NEXT;

    require SpaceTab::TextEditor;
    SpaceTab::TextEditor::edit($filename);
    return ACCEPT;
}
